/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    GameContainer: typeof import('./components/game/GameContainer.vue')['default']
    GameFAQ: typeof import('./components/game/GameFAQ.vue')['default']
    ImageCard: typeof import('./components/game/ImageCard.vue')['default']
    LanguageSwitcher: typeof import('./components/LanguageSwitcher.vue')['default']
    NewsletterSignup: typeof import('./components/NewsletterSignup.vue')['default']
    PastGamesDialog: typeof import('./components/game/PastGamesDialog.vue')['default']
    ResultScreen: typeof import('./components/game/ResultScreen.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StructuredData: typeof import('./components/StructuredData.vue')['default']
  }
}
