/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[lang]/': RouteRecordInfo<'/[lang]/', '/:lang', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    '/[lang]/about': RouteRecordInfo<'/[lang]/about', '/:lang/about', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    '/[lang]/blog/': RouteRecordInfo<'/[lang]/blog/', '/:lang/blog', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    '/[lang]/blog/[slug]': RouteRecordInfo<'/[lang]/blog/[slug]', '/:lang/blog/:slug', { lang: ParamValue<true>, slug: ParamValue<true> }, { lang: ParamValue<false>, slug: ParamValue<false> }>,
    '/[lang]/contact': RouteRecordInfo<'/[lang]/contact', '/:lang/contact', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    '/[lang]/faq': RouteRecordInfo<'/[lang]/faq', '/:lang/faq', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    '/[lang]/image/': RouteRecordInfo<'/[lang]/image/', '/:lang/image', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    '/[lang]/image/[date]': RouteRecordInfo<'/[lang]/image/[date]', '/:lang/image/:date', { lang: ParamValue<true>, date: ParamValue<true> }, { lang: ParamValue<false>, date: ParamValue<false> }>,
    '/[lang]/privacy': RouteRecordInfo<'/[lang]/privacy', '/:lang/privacy', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    '/[lang]/stats': RouteRecordInfo<'/[lang]/stats', '/:lang/stats', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    '/[lang]/terms': RouteRecordInfo<'/[lang]/terms', '/:lang/terms', { lang: ParamValue<true> }, { lang: ParamValue<false> }>,
    '/[lang]/video/[date]': RouteRecordInfo<'/[lang]/video/[date]', '/:lang/video/:date', { lang: ParamValue<true>, date: ParamValue<true> }, { lang: ParamValue<false>, date: ParamValue<false> }>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/[lang]/index.vue': {
      routes: '/[lang]/'
      views: never
    }
    'src/pages/[lang]/about.vue': {
      routes: '/[lang]/about'
      views: never
    }
    'src/pages/[lang]/blog/index.vue': {
      routes: '/[lang]/blog/'
      views: never
    }
    'src/pages/[lang]/blog/[slug].vue': {
      routes: '/[lang]/blog/[slug]'
      views: never
    }
    'src/pages/[lang]/contact.vue': {
      routes: '/[lang]/contact'
      views: never
    }
    'src/pages/[lang]/faq.vue': {
      routes: '/[lang]/faq'
      views: never
    }
    'src/pages/[lang]/image/index.vue': {
      routes: '/[lang]/image/'
      views: never
    }
    'src/pages/[lang]/image/[date].vue': {
      routes: '/[lang]/image/[date]'
      views: never
    }
    'src/pages/[lang]/privacy.vue': {
      routes: '/[lang]/privacy'
      views: never
    }
    'src/pages/[lang]/stats.vue': {
      routes: '/[lang]/stats'
      views: never
    }
    'src/pages/[lang]/terms.vue': {
      routes: '/[lang]/terms'
      views: never
    }
    'src/pages/[lang]/video/[date].vue': {
      routes: '/[lang]/video/[date]'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
