# SES Contact List
resource "aws_sesv2_contact_list" "fakeout_subscribers" {
  contact_list_name = "fakeout-new-game-subscribers"
  description      = "Subscribers for FakeOut new game notifications"

  topic {
    default_subscription_status = "OPT_IN"
    display_name                = "Daily Challenge"
    topic_name                  = "daily-challenge"
    description                 = "Receive notifications when a new daily challenge is available."
  }
}

# SES Template
resource "aws_ses_template" "fakeout_new_game" {
  name    = "fakeout-new-game"
  subject = "New FakeOut Challenge Available!"
  html    = <<EOT
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: sans-serif; background-color: #f4f4f5; padding: 20px; }
        .container { max-width: 600px; margin: 0 auto; background: white; padding: 40px; border-radius: 12px; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1); }
        .header { text-align: center; margin-bottom: 30px; }
        .title { color: #18181b; font-size: 24px; font-weight: bold; margin-bottom: 10px; }
        .content { color: #52525b; line-height: 1.6; font-size: 16px; margin-bottom: 30px; }
        .btn { display: inline-block; background-color: #4fdaf1; color: #000; font-weight: bold; padding: 12px 24px; border-radius: 8px; text-decoration: none; transition: opacity 0.2s; }
        .footer { margin-top: 40px; text-align: center; color: #a1a1aa; font-size: 12px; }
        .unsubscribe { color: #a1a1aa; text-decoration: underline; font-size: 12px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1 class="title">New FakeOut Challenge!</h1>
        </div>
        <div class="content">
            <p>Hello,</p>
            <p>A new daily challenge is available on FakeOut! Test your AI detection skills and see if you can spot the fake.</p>
            <p>Today's challenge features new image and video pairs generated by the latest AI models. Can you tell what's real?</p>
            <div style="text-align: center; margin-top: 30px;">
                <a href="https://fakeout.dev" class="btn">Play Now</a>
            </div>
        </div>
        <div class="footer">
            <p>© 2026 FakeOut. All rights reserved.</p>
            <p>
                <a href="{{unsubscribe_link}}" class="unsubscribe">Unsubscribe</a>
            </p>
        </div>
    </div>
</body>
</html>
EOT
  text    = "New FakeOut Challenge Available! Play now at https://fakeout.dev. To unsubscribe, visit: {{unsubscribe_link}}"
}

# IAM Role for notify-users Lambda
resource "aws_iam_role" "notify_users_lambda" {
  name = "notify-users-lambda-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {
          Service = "lambda.amazonaws.com"
        }
      }
    ]
  })
}

# IAM Policy for SES, Logging, and Contact List Management
resource "aws_iam_policy" "notify_users_policy" {
  name        = "notify-users-policy"
  description = "Allow Lambda to send emails via SES, manage contacts, and log to CloudWatch"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "ses:SendTemplatedEmail",
          "ses:SendEmail",
          "ses:CreateContact",
          "ses:DeleteContact",
          "ses:ListContacts"
        ]
        Resource = "*"
      },
      {
        Effect = "Allow"
        Action = [
          "logs:CreateLogGroup",
          "logs:CreateLogStream",
          "logs:PutLogEvents"
        ]
        Resource = "arn:aws:logs:*:*:*"
      }
    ]
  })
}

resource "aws_iam_role_policy_attachment" "notify_users_policy_attach" {
  role       = aws_iam_role.notify_users_lambda.name
  policy_arn = aws_iam_policy.notify_users_policy.arn
}

# Lambda function for notify-users
resource "aws_lambda_function" "notify_users" {
  filename      = "${path.module}/../notify-users/lambda.zip"
  function_name = "notify-users"
  role          = aws_iam_role.notify_users_lambda.arn
  handler       = "main.handler"
  runtime       = "python3.13"
  timeout       = 60
  memory_size   = 128

  environment {
    variables = {
      SENDER_EMAIL      = "FakeOut <${var.sender_email}>"
      CONTACT_LIST_NAME = aws_sesv2_contact_list.fakeout_subscribers.contact_list_name
    }
  }

  source_code_hash = fileexists("${path.module}/../notify-users/lambda.zip") ? filebase64sha256("${path.module}/../notify-users/lambda.zip") : null
}

# Lambda Function URL (Public)
resource "aws_lambda_function_url" "notify_users_url" {
  function_name      = aws_lambda_function.notify_users.function_name
  authorization_type = "NONE"

  cors {
    allow_credentials = true
    allow_origins     = ["https://fakeout.dev", "https://www.fakeout.dev"]
    allow_methods     = ["POST", "GET"]
    allow_headers     = ["*"]
    expose_headers    = ["keep-alive", "date"]
    max_age           = 86400
  }
}

resource "aws_lambda_permission" "notify_users_url_public" {
  statement_id           = "AllowPublicFunctionUrlInvocation"
  action                 = "lambda:InvokeFunctionUrl"
  function_name          = aws_lambda_function.notify_users.function_name
  principal              = "*"
  function_url_auth_type = "NONE"
}

# Scheduler Role
resource "aws_iam_role" "notify_scheduler_role" {
  name = "notify-users-scheduler-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Principal = {
          Service = "scheduler.amazonaws.com"
        }
        Action = "sts:AssumeRole"
      }
    ]
  })
}

resource "aws_iam_policy" "notify_scheduler_policy" {
  name        = "notify-users-scheduler-policy"
  description = "Allow Scheduler to invoke notify-users Lambda"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "lambda:InvokeFunction"
        ]
        Resource = [
          aws_lambda_function.notify_users.arn
        ]
      }
    ]
  })
}

resource "aws_iam_role_policy_attachment" "notify_scheduler_policy_attach" {
  role       = aws_iam_role.notify_scheduler_role.name
  policy_arn = aws_iam_policy.notify_scheduler_policy.arn
}

# EventBridge Scheduler for Daily Notifications
resource "aws_scheduler_schedule" "daily_notifications" {
  name       = "fakeout-daily-notification"
  group_name = "default"

  flexible_time_window {
    mode = "OFF"
  }

  # Run daily at 10 AM UTC
  schedule_expression = "cron(0 10 * * ? *)"

  target {
    arn      = aws_lambda_function.notify_users.arn
    role_arn = aws_iam_role.notify_scheduler_role.arn
    
    input = jsonencode({
      public_url = aws_lambda_function_url.notify_users_url.function_url
    })
  }
}

output "notify_users_api_url" {
  value = aws_lambda_function_url.notify_users_url.function_url
}
